### ISSUE TITLE
Unspecified error [ sqlcese40.dll ]

### ISSUE THREAD

**Issue by SoulRipper888** [judwhite/ilSFV#2]
Hello, I'm getting the following error with ilSFV release / pre-release. It used to work fine until now:

System.Data.SqlServerCe.SqlCeException (0x80004005): Unspecified error [ sqlcese40.dll ]
   at System.Data.SqlServerCe.SqlCeConnection.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at ilSFV.Program.GetOpenSettingsConnection()
   at ilSFV.Model.Settings.ProgramSettings.UpgradeSettingsDatabase()
   at ilSFV.Model.Settings.ProgramSettings..ctor()
   at ilSFV.Program.Main(String[] args)

Not sure what I can do.

Thanks in advance!

**Comment by judwhite** [comment]
@SoulRipper888 Can you try deleting the `settings.sdf` file in `C:\Users\[USER]\AppData\Local\ilSFV`? I'm not sure what caused this issue. If you have a repro steps please let me know. Thanks and sorry for the delayed response.

**Comment by SoulRipper888** [comment]
@judwhite Thanks for your reply.
I could solve the issue by removing / reinstalling the Microsoft .NET Framework.
Now everything is fine!
